export const mockData = {
  liveData: [
    {
      id: '000000123',
      name: 'KINDRED INOCENCIO',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000481',
      name: 'YMES INOCENCIO',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000123',
      name: 'KINDRED INOCENCIO',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000481',
      name: 'YMES INOCENCIO',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: '--',
      status: 'not-allowed',
    },
    {
      id: '000000123',
      name: 'KINDRED INOCENCIO',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: '--',
      status: 'not-allowed',
    },
    {
      id: '000000481',
      name: 'YMES INOCENCIO',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000123',
      name: 'KINDRED INOCENCIO',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: '--',
      status: 'not-allowed',
    },
  ],
};
